
# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirect for contact form submissions
[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

# Common security headers
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co https://maps.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: *.googleapis.com *.gstatic.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://maps.googleapis.com https://www.google.com *.googleapis.com https://api.web3forms.com; frame-src 'self' https://www.google.com;"

# Ensure sitemap.xml is properly served
[[headers]]
  for = "/sitemap.xml"
    [headers.values]
    Content-Type = "application/xml"
